import pyvista as pv
import numpy as np
import scipy.ndimage as nd
from scipy.spatial import cKDTree
import os



def generate_ischemic_scar_with_cobiveco(
    mesh_path, 
    output_path, 
    target_aha_zones, 
    tm_array_name='tm',  # Name of the transmural-coordinate array generated by Cobiveco.
    noise_scale=10.0, 
    base_threshold=0.6, 
    transmural_decay=0.4,
    bz_radius=0.2,  # cm
    MI_transmural_type = "subendo",
    MI_type = "A1",
    case_name = "IMMC210_20181126_merge_000",
    csv_output_dir = "/path/to/output/DHlab_valid_scar_new_v1"
):
    """
    Generate an ischemic scar from the Cobiveco tm coordinate, with more scar near the endocardium and less near the epicardium.
    
    Parameters:
    tm_array_name: Name of the VTU array storing the transmural coordinate (1=Endo, 0=Epi).
    noise_scale: Noise smoothness; larger values produce larger, more contiguous regions.
    base_threshold: Base threshold; lower values produce larger scars.
    transmural_decay: Strength of transmural decay.
                      0.0 = no decay (uniform scar distribution, resembling a non-ischemic pattern)
                      0.4 = moderate decay (scar concentrated in the endocardial and mid-wall layers)
                      >0.5 = strongly restricted to the endocardium (unlikely to reach the epicardium)
                      
    """
    # --- Example call. ---
    # target_zones = [7,8,9,13,14]
    # data_dir = r"/path/to/dataset/mesh_conversion_InSilicoHeartGen/sample/ensi"
    # mesh_path = f"{data_dir}/mesh_cobiveco_AHA17.vtu"
    # output_path = f"{data_dir}/mesh_cobiveco_AHA17_noise_scar.vtu"
    # generate_ischemic_scar_with_cobiveco(mesh_path=mesh_path,output_path=output_path, target_aha_zones = target_zones,noise_scale=10.0, base_threshold=0.1, transmural_decay=0.6)
    
    
    # 1. Read the mesh.
    mesh = pv.read(mesh_path)
    
    # Check the tm data.
    if tm_array_name not in mesh.point_data:
        raise ValueError(f"在 PointData 中找不到 '{tm_array_name}'。请检查数组名称。")
    
    tm_values = mesh.point_data[tm_array_name] # 1.0(Endo) -> 0.0(Epi)
    
    # 2. Generate the 3D noise field that defines region shape.
    bounds = mesh.bounds
    grid = pv.ImageData()
    grid.dimensions = (100, 100, 100) # Resolution.
    grid.origin = (bounds[0], bounds[2], bounds[4])
    grid.spacing = ((bounds[1]-bounds[0])/100, (bounds[3]-bounds[2])/100, (bounds[5]-bounds[4])/100)
    
    raw_noise = np.random.rand(*grid.dimensions)
    smooth_noise = nd.gaussian_filter(raw_noise, sigma=noise_scale)
    # Normalize to [0, 1].
    smooth_noise = (smooth_noise - smooth_noise.min()) / (smooth_noise.max() - smooth_noise.min())
    
    grid.point_data['noise_field'] = smooth_noise.flatten(order='F')
    sampled_mesh = mesh.sample(grid)
    
    noise_values = sampled_mesh.point_data['noise_field']
    aha_labels = mesh.point_data['aha']
    
    # Create an empty scar array.
    # --- Key change: initialize as int8 (0=Healthy, 1=Scar, 2=BZ). ---
    final_scar_mask = np.zeros(mesh.n_points, dtype=np.uint8)

    # ==========================================
    # Core change: define the scar first, then define the border zone by distance.
    # ==========================================
    
    # 1. Extract the target region of interest.
    roi_mask = np.isin(aha_labels, target_aha_zones)
    roi_indices = np.where(roi_mask)[0]
    
    if len(roi_indices) == 0:
        print("警告: 指定的 AHA 区域未找到点")
        return

    # Extract region-of-interest attributes.
    roi_noise = noise_values[roi_indices]
    roi_tm = tm_values[roi_indices]
    
    # Normalize noise within the region.
    if roi_noise.max() > roi_noise.min():
        roi_noise_norm = (roi_noise - roi_noise.min()) / (roi_noise.max() - roi_noise.min())
    else:
        roi_noise_norm = roi_noise 

    # Apply the left-ventricular restriction for subendocardial scars.
    roi_tv = None
    if MI_transmural_type == "subendo":
        if 'tv' in mesh.point_data:
            roi_tv = mesh.point_data['tv'][roi_indices]
        else:
            MI_transmural_type = "transmural"

    # 2. Determine the core scar from noise and transmural depth only, without considering the border zone.
    dynamic_threshold = base_threshold + (1.0 - roi_tm) * transmural_decay
    
    if MI_transmural_type == "subendo" and roi_tv is not None:
        # Strictly restrict the scar to the endocardial side and left ventricle.
        is_scar_local = (roi_noise_norm > dynamic_threshold) & (roi_tv < 0.5) & (roi_tm > 0.5)
    else:
        # Transmural mode.
        is_scar_local = (roi_noise_norm > dynamic_threshold)
    
    # Convert local scar indices back to global indices.
    global_scar_indices = roi_indices[is_scar_local]
    
    # If no scar was generated, record it in the log and return.
    if len(global_scar_indices) == 0:
        with open(f"{csv_output_dir}/scar_generation_log.txt", "a") as log_file:
            log_file.write(f"{case_name}, {MI_type}, {MI_transmural_type}: No Scar generated.\n")
        

    # Fill the scar region (label 1).
    final_scar_mask[global_scar_indices] = 1
    
    # 3. Generate the border zone from geometric distance.
    #    Within the region of interest, find non-scar points close to the scar.
    
    if bz_radius > 0:
        print(f"正在计算 BZ 区域 (半径 {bz_radius})...")
        
        # Get the physical coordinates of scar points.
        scar_points = mesh.points[global_scar_indices]
        
        # Get healthy points in the region of interest as candidate border-zone locations.
        is_healthy_global_mask = (final_scar_mask == 0)
        global_healthy_indices = np.where(is_healthy_global_mask)[0]
        
        if len(global_healthy_indices) > 0:
            healthy_points = mesh.points[global_healthy_indices]
            
            # --- Use a KDTree to accelerate nearest-neighbor search. ---
            # Build an index tree for scar points.
            tree = cKDTree(scar_points)
            
            # Query the distance from each healthy point to its nearest scar point (k=1).
            # dists contains distances; _ contains unused corresponding indices.
            dists, _ = tree.query(healthy_points, k=1)
            
            # Find points closer than the specified radius.
            is_bz_local = dists <= bz_radius
            
            # Map back to global indices.
            global_bz_indices = global_healthy_indices[is_bz_local]
            
            # Fill the border zone (label 2).
            final_scar_mask[global_bz_indices] = 2

    # ==========================================
    # End of modification.
    # ==========================================
    
    mesh.point_data['Scar'] = final_scar_mask.astype(np.int8)
    
    # # --- Visual verification. ---
    # plotter = pv.Plotter()
    # plotter.add_mesh(mesh, scalars='Scar', 
    #                     cmap=['white', 'red', 'blue'], # Corresponds to 0, 1, and 2.
    #                     clim=[0, 2], # Fix the color range to [0, 2].
    #                     categories=True,
    #                     show_edges=False,
    #                     n_colors=3,
    #                     annotations={0:'Healthy', 1:'Scar', 2:'BZ'})

    # plotter.add_axes() # Adding axes is strongly recommended for orientation.
    # # cpos = plotter.show(return_cpos=True)
    # # print("Save the camera position for later inspection:", cpos)
    # my_cpos = [(-19.28571952007316, 6.930280145499737, -1.6553392925770958),
    #            (5.790475468039389, -3.3232884665313227, 1.849069878570795),
    #            (-0.21339307149521425, -0.19466896861107008, 0.9573752606463888)]
    # plotter.show(cpos=my_cpos)

    # Compute the mean depth of the scar region.
    avg_tm = np.mean(mesh.point_data[tm_array_name][final_scar_mask == 1])
    print(f"Scar 平均透壁深度 (tm): {avg_tm:.3f} (接近1=内膜, 接近0=外膜)")
    
    # Compute scar burden.
    scar_burden = np.sum(final_scar_mask == 1) / mesh.n_points * 100.0
    print(f"Scar Burden: {scar_burden:.2f}%")
        
    # # 5. Save the result.
    if case_name == "IMMC210_20181126_merge_000":
        mesh.save(output_path)
    
    # Save mesh.point_data['Scar'] to CSV, with scar and border-zone nodes in separate files.
    # Use one-based indices for compatibility with the original MATLAB program.
    scar_nodes = np.where(final_scar_mask == 1)[0] + 1
    bz_nodes   = np.where(final_scar_mask == 2)[0] + 1
    
    # 3. Construct CSV filenames from output_path.
    scar_csv_name = f"{case_name}_coarse_new_v1_lvscarnodes_{MI_type}_{MI_transmural_type}.csv"
    bz_csv_name   = f"{case_name}_coarse_new_v1_lvborderzonenodes_{MI_type}_{MI_transmural_type}.csv"
    
    scar_csv_path = os.path.join(csv_output_dir, case_name, scar_csv_name)
    bz_csv_path   = os.path.join(csv_output_dir, case_name, bz_csv_name)
    
    # 4. Save as integer-formatted CSV.
    # fmt='%d' writes integers without decimal points.
    np.savetxt(scar_csv_path, scar_nodes, fmt='%d', delimiter=',')
    np.savetxt(bz_csv_path, bz_nodes, fmt='%d', delimiter=',')
    
    return avg_tm, scar_burden

def main_MI_area():
    # Example call.
    root_dir = "/path/to/dataset/mesh_conversion_InSilicoHeartGen"
    csv_output_dir = "/path/to/output/DHlab_valid_scar_new_v1"
    os.makedirs(csv_output_dir, exist_ok=True)
    
    case_list = []

    for case_name in os.listdir(root_dir):
        os.makedirs(f"{csv_output_dir}/{case_name}", exist_ok=True)
        # case_name = "IMMC210_20181126_merge_000"
        data_dir = f"/path/to/dataset/mesh_conversion_InSilicoHeartGen/{case_name}/ensi"
        
        MI_zone_dict = {
            'A1': [7,8,9,13,14],  # Septal
            'A2': [13,14,15,16,17],  # Apical anteroseptal
            'A3': [1,2,3,7,8,9,13,14,15,16,17],  # Extensive anterior
            'A4': [1,6,7,12,13,16,17],  # Limited anterior
            'B1': [5,6,11,12,16],  # Lateral
            'B2': [3,4,9,10,14,15,17],  # Inferior
            'B3': [3,4,5,9,10,11,12,15,16]  # Inferolateral
        }
        
        MI_transmural_types = ['subendo', 'transmural']
        
        size_types = ['small', 'large']
        
        for MI_type, target_zones in MI_zone_dict.items():
            for MI_transmural_type in MI_transmural_types:
                print(f"正在生成 MI 类型 {MI_type}，透壁衰减模式 {MI_transmural_type} ...")
                if MI_type == 'B1':
                    for size in size_types:
                        if size == 'small':
                            base_threshold = 0.7
                            transmural_decay = 0.2
                            MI_type_new = 'B1_small'
                        else:
                            base_threshold = 0.5
                            transmural_decay = 0
                            MI_type_new = 'B1_large'
                        mesh_path = f"{data_dir}/mesh_cobiveco_AHA17.vtu"
                        output_path = f"{csv_output_dir}/{case_name}/mesh_cobiveco_AHA17_noise_scar_{MI_type_new}_{MI_transmural_type}.vtu"
                        avg_tm, scar_burden = generate_ischemic_scar_with_cobiveco(
                            mesh_path=mesh_path,
                            output_path=output_path, 
                            target_aha_zones=target_zones,
                            noise_scale=10, 
                            base_threshold=base_threshold, 
                            transmural_decay=transmural_decay,
                            bz_radius=0.25,
                            MI_transmural_type=MI_transmural_type,
                            MI_type = MI_type_new,
                            case_name = case_name,
                            csv_output_dir = csv_output_dir,
                        )
                        case_list.append((case_name, MI_type_new, MI_transmural_type, avg_tm,scar_burden))
                    
                else:
                    MI_type_new = MI_type
                    mesh_path = f"{data_dir}/mesh_cobiveco_AHA17.vtu"
                    output_path = f"{csv_output_dir}/{case_name}/mesh_cobiveco_AHA17_noise_scar_{MI_type_new}_{MI_transmural_type}.vtu"
                    avg_tm, scar_burden = generate_ischemic_scar_with_cobiveco(
                        mesh_path=mesh_path,
                        output_path=output_path, 
                        target_aha_zones=target_zones,
                        noise_scale=10, 
                        base_threshold=0.5, 
                        transmural_decay=0,
                        bz_radius=0.25,
                        MI_transmural_type=MI_transmural_type,
                        MI_type = MI_type_new,
                        case_name = case_name,
                        csv_output_dir = csv_output_dir,
                    )
                
                    case_list.append((case_name, MI_type_new, MI_transmural_type, avg_tm,scar_burden))
    # Save the summary CSV.
    summary_path = os.path.join(csv_output_dir, "scar_generation_summary.csv")
    with open(summary_path, "w") as f:
        f.write("CaseName,MI_Type,MI_Transmural_Type,Avg_tm,Scar_Burden(%)\n")
        for case_name, MI_type, MI_transmural_type, avg_tm, scar_burden in case_list:
            f.write(f"{case_name},{MI_type},{MI_transmural_type},{avg_tm:.4f},{scar_burden:.2f}\n")
            
if __name__ == "__main__":
    main_MI_area()
    
